prepare:
    cargo sqlx prepare -- --all-targets

test--select: 
    cargo test print_data_from_db -- --nocapture

export_db:
    export DATABASE_URL="postgres://admin:admin@localhost/test"

new_db:
    sqlx db create && sqlx migrate run